---
# This role deploys the mongodb processes and sets up settings.

- name: Include OS-specific variables defaults
  include_vars:
    file: "defaults/{{ ansible_os_family }}.yml"

- name: Install packages dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mongodb_packages_dependencies | default([]) }}"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
