---
- name: Include distribution-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Add repo key
  apt_key:
    keyserver: "{{ mongodb_url_apt_key }}"
    id: "{{ mongodb_id_apt_key }}"

- name: Add repo
  apt_repository:
    repo: "{{ mongodb_repository }}"
    update_cache: yes

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ mongodb_packages }}"
  notify:
  - restart mongod
  - enable mongod
